### ISSUE TITLE
Add Elasticsearch as provider

### ISSUE THREAD

**Issue by henryx** [facette/facette#293]
Currently facette doesn't support Elasticsearch as data provider. Your support can be appreciated because it permits to use an ELK source base without reverse the database

**Comment by falzm** [comment]
Problem with Elasticsearch is that it's not really a pure time series datastore but a search engine – not even a database –, very few people use it to store time series and if they do they probably do it in their own way, which might be quite different from one to another. No standardization implies it's very hard for us to develop a connector since it should be very flexible to fit anybody's use case...

**Comment by falzm** [comment]
Unless someone contributes a backend connector for using Elasticsearch as a provider, we won't implement it for the reason stated above.
