### ISSUE TITLE
Installation problems on Windows

### ISSUE THREAD

**Issue by tdewolff** [facette/facette#322]
Makefiles are the worst on Windows, so I wasn't surprised it didn't work, but trying to manually build the commands the regular way using Go gives errors such as:

```package facette/backend: unrecognized import path "facette/backend" (import path does not begin with hostname)```

But would it be possible to have a Windows version pre-build? Or how do I install this on a Windows machine?

**Comment by vbatoufflet** [comment]
Hi @tdewolff,

I don't have a Windows machine in order to perform any test, so Windows is not officially supported.

But I guess the problems come from missing GOPATH values, normally handled by the Makefile.

You should try to define `GOPATH=path/to/sources;path/to/sources/vendor`, then to execute for example:
```
go build -o path/to/destination/facette.exe ./src/cmd/facette
go build -o path/to/destination/facettectl.exe ./src/cmd/facettectl
```

**Comment by vbatoufflet** [comment]
Closing this issue for now. Please reopen if needed.
