### ISSUE TITLE
Graphite URLs are not escaped.

### ISSUE THREAD

**Issue by maximevalette** [facette/facette#84]
I wondered why my Graphite graphs were not showing anything, and after looking at the Graphite logs I noticed the issue:

```
127.0.0.1 - - [30/Jul/2014:08:53:19 +0200] "GET /render?format=json&target=legendValue(alias(myohst.apache2.u, 'Open'), 'min', 'max', 'avg', 'last')&from=-3600s&until=-0s HTTP/1.1" 200 184 "-" "Facette"
```

The characters are not escaped when building the URLs in the `graphite.go` connector — A correct HTTP request would look like this:

```
127.0.0.1 - - [30/Jul/2014:08:53:19 +0200] "GET /render?format=json&target=legendValue(alias(myohst.apache2.u,%20%27Open%27),%20%27min%27,%20%27max%27,%20%27avg%27,%20%27last%27)&from=-3600s&until=-0s HTTP/1.1" 200 641 "-" "Facette"
```

I would be happy to directly fix this in the file but I don't know much about Go. :)

**Comment by tmack0** [comment]
The current 0.3.0 .deb package (amd64 wheezy) seems to still have this issue or a regression of it. Seeing \ escaped quotes in my graphite access log instead of % url escaped ones:
[02/Dec/2015:17:03:44 -0800] "GET /render?format=json&target=alias(collectd.graphite.interface-eth0.if_packets.rx, \"series0\")&target=alias(collectd.graphite.load.load.shortterm, \"series1\")&target=alias(collectd.graphite.interface-eth0.if_packets.tx, \"series2\")&from=-3600s&until=-0s HTTP/1.1"
results in NO DATA instead of graphs.
should be 
"GET //render?format=json&target=alias(collectd.graphite.interface-eth0.if_packets.rx,%20\\%22series0\\%22)&target=alias(collectd.graphite.load.load.shortterm,%20\\%22series1\\%22)&target=alias(collectd.graphite.interface-eth0.if_packets.tx,%20\\%22series2\\%22)&from=-3600s&until=-0s HTTP/1.1"
(per graphite log sending the URL via firefox, which auto-fixed/escaped things).
